[package]
distribution = "2201.10.0"
org = "ballerinax"
name = "hubspot.crm.pipelines"
version = "1.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["hubspot", "crm", "pipelines"]
# icon = "icon.png" # TODO: Add icon
repository = "https://github.com/ballerina-platform/module-ballerinax-hubspot.crm.pipelines"

[build-options]
observabilityIncluded = true

[platform.java17]
graalvmCompatible = true
